### ISSUE TITLE
poll_client returns none 

### ISSUE THREAD

**Issue by VibhavariMandal** [TAXIIProject/yeti#89]
hi,

I am using Yeti to push and poll. Inbox_client is successful but poll returns nothing from the default collection. Where can i see where is my file getting pushed in DB and why is poll returning none,

[root@localhost ~]# poll_client -u  http://localhost:8080/services/poll/
Request:

Message Type: Poll_Request
Message ID: 8483221472561037604
  Collection Name: default
  Excl. Begin TS Label: None
  Incl. End TS Label: None
  === Poll_Parameters ===
    Response type: FULL

Response:

Message Type: Poll_Response
Message ID: 4221234838242163321; In Response To: 8483221472561037604
  Collection Name: default
  More: False
  Result ID: None
  Result Part Num: 1
  === Record Count ===
    Record Count: 0
  Incl. End TS Label: 2017-08-21T06:23:11.897006+00:00

**Comment by gtback** [comment]
Thanks for the question, @VibhavariMandal . 

I'd have to set up a new test environment to confirm this, but you should be able to go to `/admin` to view the admin interface for YETI, which shows all the content in the system. Also, make sure the collection you're putting content into is the same one you're querying with the poll_client. If it doesn't work with the default collection, maybe try explicitly setting the collection?

If that doesn't help, feel free to let me know the exact commands you're running (both the inbox and poll commands) and I'll try to reproduce. Thanks again!

**Comment by VibhavariMandal** [comment]
hi Greg, 
thanks alot for your response.
Btw, I have accessed yeti sing GUI using admin and I could see my STIX files pushed in content block, but using cli, I dont get any files polled. Also, I am pushing into default collection and by default poll also retrieves from default collection, push is successful but poll is not. Please look into it .
Below is the command of inbox_client and poll. Also I am attaching snapshot of GUI.


root@vatd:~# inbox_client -u http://10.213.18.193:8080/services/inbox/
Request:

Message Type: Inbox_Message
Message ID: 5224570414593728399
  Message: None
  Message has 1 Content Blocks
  === Content Block ===
    Content Binding: urn:stix.mitre.org:xml:1.1.1
    Content length: 2250
    (Content not printed for brevity)
    Message: None
    Padding: None

Response:

Message Type: Status_Message
Message ID: 5146559581569589083; In Response To: 5224570414593728399
Status Type: SUCCESS

root@vatd:~# poll_client -u  http://10.213.18.193:8080/services/poll/
Request:

Message Type: Poll_Request
Message ID: 4634770275962907233
  Collection Name: default
  Excl. Begin TS Label: None
  Incl. End TS Label: None
  === Poll_Parameters ===
    Response type: FULL

Response:

Message Type: Poll_Response
Message ID: 6894871665563005906; In Response To: 4634770275962907233
  Collection Name: default
  More: False
  Result ID: None
  Result Part Num: 1
  === Record Count ===
    Record Count: 0
  Incl. End TS Label: 2017-08-22T06:00:45.932409+00:00

root@vatd:~#
![image](https://user-images.githubusercontent.com/31065756/29550897-e02ef6ac-872d-11e7-9bb6-09dd8f9818fb.png)

**Comment by gtback** [comment]
I think the issue is that the `inbox_client` by default doesn't specify a Collection name (so the content block gets saved, but is not associated with the default Collection (named `default`). When I run `inbox_client -u http://127.0.0.1:8080/services/inbox/ --dcn default`, then `poll_client -u http://127.0.0.1:8080/services/poll/`, I get the corresponding Content block returned. 

I think part of the confusion is that there is a default STIX package built into libtaxii, but it doesn't pass a default collection name. If I had to suggest a way to make it more intuitive, I would disable the default package for `inbox_client`, and add an option `--use-default-package` to use it, but otherwise error if you don't provide a file. 

@MarkDavidson , thoughts?

**Comment by VibhavariMandal** [comment]
Thanks alot Greg ! that helps :) the issue is solved now
